stages:
  - Build image
  - Push to Docker Hub

docker build:
  stage: Build image
  services:
  - docker:dind
  image: docker
  variables:
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
  - docker info
  - docker build -t python-dev-docker .

docker push:
  stage: Push to Docker Hub
  only:
  - master
  script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push ebewo/python-dev-docker && docker image rm ebewo/python-dev-docker