image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - Build image
  - Push to Docker Hub

# before_script:
  # - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin

docker build:
  stage: Build image

  script:
  - docker info
  - docker build -t python-dev-docker .

docker push:
  stage: Push to Docker Hub
  only:
  - master
  script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push ebewo/python-dev-docker
  - docker image rm ebewo/python-dev-docker